# Generated by Django 2.2 on 2019-04-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayoff', '0002_auto_20190429_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayoff',
            name='reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dayoff',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'ลากิจ'), (1, 'ลาป่วย')], default=0),
        ),
    ]
