# Generated by Django 2.2 on 2019-04-29 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dayoff', '0004_auto_20190429_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoff',
            name='approve_status',
            field=models.SmallIntegerField(choices=[(0, 'อนุมัติ'), (1, 'ไม่อนุมัติ'), (2, 'รอการอนุมัติ')], default=2, verbose_name='อนุมัติ'),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='create_by',
            field=models.ForeignKey(db_column='create_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ขอลาโดย'),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='date_end',
            field=models.DateField(null=True, verbose_name='ถึงวันที่'),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='date_start',
            field=models.DateField(null=True, verbose_name='ตั้งแต่วันที่'),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='reason',
            field=models.TextField(null=True, verbose_name='เนื่องจาก'),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'ลากิจ'), (1, 'ลาป่วย')], default=0, verbose_name='ประเภท'),
        ),
    ]
