# Generated by Django 2.2 on 2019-04-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
