# Generated by Django 2.2 on 2019-04-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_poll_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='email',
        ),
        migrations.AlterField(
            model_name='poll',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
